site_name: "Tôi không biết code"
# site_url: https://itdn.site/mysite
theme: 
  logo: img/dino.png
  favicon: img/dino.png
  name: material
  language: vi
  palette: 
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
        # primary: black
plugins:
 - search
 - blog
#  - social
nav:
  - Home: index.md
  - Blog: blog/index.md
  - Docker: 
    - Install: docker.md
    - Swarm: swarm.md

# site_name: Test site_name:
# theme: