site_name: Cimon Document
# site_url: https://itdn.site/mysite
theme: 
  name: material
plugins:
 - search
nav:
  - Home:
    - Test1: index.md
  - Test: test.md

# site_name: Test site_name:
# theme: