site_name: "Tôi không biết code"
# site_url: https://itdn.site/mysite
theme: 
  logo: img/dino.png
  favicon: img/dino.png
  name: material
  language: vi
  features: 
    # - navigation.footer
  palette: 
    - scheme: default
      primary: "blue grey"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        # primary: black
# extra: 
#   social:
#   - icon: fontawesome/brands/github
#   - link: https://facebook.com/tan.odd96
plugins:
 - search
 - blog
#  - social
nav:
  - Home: index.md
  - Blog: blog/index.md
  - Docker: 
    - Install: docker.md
    - Swarm: swarm.md
    - Cheatsheet: docker-cheatsheet.md
  - Ubuntu:
    - Cheatsheet: ubuntu.md
  - Traefik: traefik-index.md
  - Markdown: markdown.md
  - Source: 
    - Document: source_document.md
# site_name: Test site_name:
# theme: